language: php

php:
  - 5.6
  - 7.2
  - 7.4

before_script:
  - travis_retry composer self-update
  - travis_retry COMPOSER_MEMORY_LIMIT=-1 composer install

script: vendor/bin/phpunit --verbose

notifications:
  email:
    on_success: never